# Generated by Django 4.0.4 on 2022-05-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='car_model',
            field=models.CharField(default='mercedes', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='car_year',
            field=models.IntegerField(default=2000),
        ),
    ]
