# Generated by Django 4.0.4 on 2022-04-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_informed_buyers',
            field=models.BooleanField(default=False),
        ),
    ]
