# Generated by Django 4.0.4 on 2022-04-24 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_is_informed_buyers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='is_informed_buyers',
            new_name='is_informed_buyer',
        ),
    ]
