# Generated by Django 4.0.4 on 2022-04-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_rename_is_informed_buyers_car_is_informed_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='is_informed_buyer',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
